# Import libraries
import pickle
import streamlit as st
import numpy as np

# Load the pre-trained model and the scaler
model = pickle.load(open(r"C:\Users\sunil\Desktop\DK\vs code\INVERSTMENT PREDICTION\inverstment.pkl", "rb"))
scaler = pickle.load(open(r"C:\Users\sunil\Desktop\DK\vs code\INVERSTMENT PREDICTION\scaler.pkl", "rb"))  # Assuming you have a scaler file from training

# Title for the app
st.title("Marketing Spend Optimizer App")

# Text box
st.write("This is an app that predicts the profit you earn based on money spent on Digital Marketing, Promotion, and Research.")
st.write("Please provide necessary details to get a proper output.")

# Input fields
digital_marketing = st.number_input("Digital Marketing", min_value=0.0, max_value=1e10, value=0.0, step=1.0)
promotion = st.number_input("Promotion", min_value=0.0, max_value=1e10, value=0.0, step=1.0)
research = st.number_input("Research", min_value=0.0, max_value=1e10, value=0.0, step=1.0)

# Create the button
if st.button("Show Profit"):
    # Combine inputs into a single array
    input_array = np.array([[digital_marketing, promotion, research,0,0,0]])

    # Scale the input data using the pre-fitted scaler
    input_scaled = scaler.transform(input_array)

    # Predict the profit using the model
    prediction = model.predict(input_scaled)

    # Display the success message with the predicted profit
    st.success(f"The estimated profit is: ${prediction[0]:,.2f}")

    # Display a final message
    st.write("The output is an approximate value generated by the model. Thank you for using the app!")
